### ISSUE TITLE
Example value of api method with FromRoute and FromBody don't use the FromBody parameter

### ISSUE THREAD

**Issue by cfeltz34** [mattfrear/Swashbuckle.AspNetCore.Filters#163] opened 2020-11-05 11:38 UTC
**Step to reproduce :** 
I create a new method on my api with 2 parameters **FromRoute** and **FromBody** : 
        public class TestModelDTO {
            public int code { get; set; }
            public string message { get; set; }
        } 
        [HttpPost("Test/{idTest}")]
        public ActionResult<IApiMessage> Test([FromRoute] string idTest, [FromBody] TestModelDTO data)
        {
            _logger.LogInformation($"test: {idTest} - {data.message}");
            return null;
        }

I open my swagger page : 
--> The example value of my method don't use TestModelDTO but an empty string example --> ''
![image](https://user-images.githubusercontent.com/45885838/98236187-3963d780-1f63-11eb-83dd-38a45130b18a.png)

Expected value : 
--> the example value should be 
{
  "code": 0,
  "message": "string"
}

**Solution** : 
To fix the issue, may be just modify "**ServiceProviderExamplesOperationFilter** class / méthod **SetRequestExamples** to browse only body parameters : 
![image](https://user-images.githubusercontent.com/45885838/98236491-b55e1f80-1f63-11eb-908f-d581fdf8c1f1.png)

**Comment by mattfrear** [comment] 2020-11-09 21:23
I can't reproduce this bug. How are you defining the example for TestModelDTO?

This is a working example:
```csharp
    public class ValuesController : Controller
    {

        public class TestModelDTO
        {
            public int code { get; set; }
            public string message { get; set; }
        }

        public class TestModelDtoExample : IExamplesProvider<TestModelDTO>
        {
            public TestModelDTO GetExamples()
            {
                return new TestModelDTO { code = 200, message = "success" };
            }
        }

        [HttpPost("Test/{idTest}")]
        public ActionResult Test([FromRoute] string idTest, [FromBody] TestModelDTO data)
        {
            return null;
        }
}
```

![image](https://user-images.githubusercontent.com/169179/98598025-b5cd3080-233e-11eb-99a2-67e09d1e82b8.png)

**Comment by mattfrear** [comment] 2020-11-17 23:01
Can't reproduce, closing.

**Closed by mattfrear** 2020-11-17 23:01 UTC
