### ISSUE TITLE
Invalid generic types when using generic provider (IExampleProvider<T>)

### ISSUE THREAD

**Issue by JasonXtreme** [mattfrear/Swashbuckle.AspNetCore.Filters#75] opened 2018-11-28 14:06 UTC
Consider the code:

```
public class Examples
    {     
        public class GeneralExample<T> : IExamplesProvider<T> where T : class
        {
            public T GetExamples()
            {                               
                        var AllFakers = from x in Assembly.GetExecutingAssembly().GetTypes()
                                        let y = x.BaseType
                                        where !x.IsAbstract && !x.IsInterface &&
                                        y != null && y.IsGenericType &&
                                        y.GetGenericTypeDefinition() == typeof(AutoFaker<>)
                                        select x;
                        var fakerType = AllFakers.FirstOrDefault(e => e.BaseType.GenericTypeArguments[0] == typeof(T));
                        if (fakerType != null)
                        {
                            var autoFaker = (AutoFaker<T>)(Activator.CreateInstance(fakerType));
                            return autoFaker.Generate();
                        }
                        return default(T);                  
                }
            }
        }
    }
```
Because every type used in every endpoint is considered, aspnetcore throws an ArgumentException when the T is something non-generic, like a string, or a Guid?, probably from line:

`var exampleProviderType = typeof(IExamplesProvider<>).MakeGenericType(type);`

To bypass the issue, I've edited the ServiceProviderExamplesOperationFilter.GetExampleForTypeFromServiceProvider function to include the check:

```
 bool IsSimpleType(Type mtype)
            {
                return
                    mtype.IsValueType ||
                    mtype.IsPrimitive ||
                    new Type[] {
                typeof(string),
                typeof(decimal),
                typeof(DateTime),
                typeof(DateTimeOffset),
                typeof(TimeSpan),
                typeof(Guid),
                typeof(decimal?),
                typeof(DateTime?),
                typeof(DateTimeOffset?),
                typeof(TimeSpan?),
                typeof(Guid?)
                    }.Contains(mtype) ||
                    Convert.GetTypeCode(mtype) != TypeCode.Object;
            }
```

in the function:

```
 bool IsPrimitiveType()
            {
                return !type.GetTypeInfo().IsClass && !type.GetTypeInfo().IsGenericType || **IsSimpleType(type);**
            }
```
I've also encapsulated lines 

```
var exampleProviderType = typeof(IExamplesProvider<>).MakeGenericType(type);
                var exampleProviderObject = serviceProvider.GetService(exampleProviderType);

                if (exampleProviderObject == null)
                {
                    return null;
                }

                var methodInfo = exampleProviderType.GetMethod("GetExamples");
                var example = methodInfo.Invoke(exampleProviderObject, null); // yay, we've got the example! Now just need to set it.
                return example;
```
in a try/catch, returning null if an exception is thrown by an unpredicted sample object.

The workaround suits my need fine, but a finer consideration is probably in order to make sure all samples are returned if possible.

**Comment by mattfrear** [comment] 2018-11-29 17:46
OK, cool. Would you like to raise a PR for this? Where did you get the list of types to include in your IsSimpleType method, i.e. `typeof(string), typeof(decimal)`, etc? I'm wondering if there are any that you've missed?

**Comment by JasonXtreme** [comment] 2018-11-30 09:09
Hi, I've not done a push request yet, I'd have to read a few docs first not to botch something up :D 
The types are a list of primitive and common non-primitive types that've cause problems for me before, I'm pretty sure the list is incomplete, but have no way of verifying it. Come to think of it, if the throw when using 
`var exampleProviderType = typeof(IExamplesProvider<>).MakeGenericType(type);`
is caught in a try/catch, you don't actually need to check types, just return null and it seems to work just fine. Perhaps this could be handled by way of a new exception type? It's be well hidden for debugging though...

**Comment by mattfrear** [comment] 2018-12-02 01:50
Your code as-is won't work unfortunately - because .netstandard1.6 doesn't have Type.IsValueType or Type.IsPrimitiveType. So we could ignore that and just add a try / catch as you have suggested.

I'm happy to do that, but I would need to be able to write a failing test first, which I am unable to do. When `var exampleProviderType = typeof(IExamplesProvider<>).MakeGenericType(type);` throws an exception, what Type is type? I tried DateTime, and that works fine and does not throw an exception.

See the existing test Apply_WhenRequestIsAntInt_ShouldNotThrowException for an idea of what I am trying to do.

**Comment by JasonXtreme** [comment] 2018-12-04 11:36
I'm sorry for the late reply here. I've rechecked my code and noticed the base of the problem lies somewhere else. My instantiator class looks like this (see example above):

`public class GeneralExample<T> : IExamplesProvider<T> where T : class`

What actually caused my exception here is:

the line
`var exampleProviderType = typeof(IExamplesProvider<>).MakeGenericType(type);`
breaks the 'where T: class' constraint, and that throws an exception. So in truth, your code works just fine, it's just not compatible with my use. I suggest adding some sort of mechanism so that these constraints can be passed on to your functions. 

What happened here is that the MakeGenericType tried instantiating the `Nullable<Guid>` type and fitting it into the class above, which of course failed, as `Nullable<Guid>` is not a class. As the MakeGenericType is called somewhere in your code, it could not be caught properly and caused an application wide crash, but again, this is just for me. Sorry for the misunderstanding :)

**Comment by mattfrear** [comment] 2018-12-08 08:01
I'm still struggling to understand the problem here - or at least reproduce it. I'm all for making my code more robust, but I'm reluctant to make any changes without first having a failing test.

I have again attempted to write a failing test where the line containing `MakeGenericType(type)` will fail, by writing a test where `type` is `Nullable<Guid>`. The commit with this test is here:
https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/commit/6aa340b0d5c411d46c476ae52c3fc54beaefa5ed

However, the test passes. Maybe you could have a go at writing a failing test in that branch?

**Comment by JasonXtreme** [comment] 2018-12-10 11:55
Well, I was sure I wrote a response to this. I was wrong. The problem is not the MakeGenericType(type), that'll instantiate almost anything. The problem occurs, when the "T" in
`public class GeneralExample<T> : IExamplesProvider<T> where T : class`
is not a class type. The MakeGenericType has no mechanism to check whether T is a class, and the MakeGenericType passes a Nullable<Guid> as T for example into the GenericExample<T>. This violates the T:class constraint and throws a runtime exception. It's not a direct problem, more of a runtime one. I'll check your test and see if I can reproduce this in a testable manner.

**Comment by JasonXtreme** [comment] 2018-12-10 12:00
Ok, so a failing test would be:
```
[Fact]
        public void Apply_WhenRequestIsANullableGuid_ShouldNotThrowException()
        {
            // Arrange
            serviceProvider.GetService(typeof(IExamplesProvider<Guid?>)).Returns(new GuidExample**<Guid?>**());
            var customerParameter = new BodyParameter { In = "body", Schema = new Schema { Ref = "#/definitions/CustomerId" } };
            var operation = new Operation { OperationId = "foobar", Parameters = new[] { customerParameter } };
            var parameterDescriptions = new List<ApiParameterDescription>() { new ApiParameterDescription { Type = typeof(Nullable<Guid>), Name = "customerId" } };
            var filterContext = FilterContextFor(typeof(FakeActions), nameof(FakeActions.RequestTakesANullableGuid), parameterDescriptions);
             // Act
            sut.Apply(operation, filterContext);
             // Assert
            var actualParameterExample = Guid.Parse(customerParameter.Schema.Example.ToString());
            var expectedExample = new GuidExample**<Guid?>**().GetExamples().Value;
            actualParameterExample.ShouldBe(expectedExample);
        }
```

```
using System;
 namespace Swashbuckle.AspNetCore.Filters.Test.TestFixtures.Examples
{
    public class GuidExample<T> : IExamplesProvider<T> where T:class, new()
    {
        public T GetExamples()
        {
            return new T();
        }
    }
}
```

Where the line
`return new T();`
would be an autofaker generator or something generic for classes.

**Comment by mattfrear** [comment] 2019-01-03 09:30
Hi again,

I've had another attempt at creating a failing test, based on your last post. The test looks like this:
```csharp
        private class GenericExampleProvider<T> : IExamplesProvider<T>
        {
            public const string Blah = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";
            public T GetExamples()
            {
                if (typeof(T) == typeof(Guid?))
                {
                    return (T)(object)new Guid(Blah);
                }

                return default(T);
            }
        }

        [Fact]
        public void Apply_WhenExampleProviderIsGenericAndRequestIsANullableGuid_ShouldNotThrowException()
        {
            // Arrange
            serviceProvider.GetService(typeof(IExamplesProvider<Guid?>)).Returns(new GenericExampleProvider<Guid?>());
            var customerParameter = new BodyParameter { In = "body", Schema = new Schema { Ref = "#/definitions/CustomerId" } };
            var operation = new Operation { OperationId = "foobar", Parameters = new[] { customerParameter } };
            var parameterDescriptions = new List<ApiParameterDescription>() { new ApiParameterDescription { Type = typeof(Nullable<Guid>), Name = "customerId" } };
            var filterContext = FilterContextFor(typeof(FakeActions), nameof(FakeActions.RequestTakesANullableGuid), parameterDescriptions);

            // Act
            sut.Apply(operation, filterContext);

            // Assert
            var actualParameterExample = customerParameter.Schema.Example.ToString();
            var expectedExample = GenericExampleProvider<Guid?>.Blah;
            actualParameterExample.ShouldBe(expectedExample);
        }
```

However, this test passes. I'm not sure where to go from here.

**Comment by mattfrear** [comment] 2019-01-03 09:35
Ah sorry, my test which passes has no generic constraint, i.e. `where T : class`, which you mentioned earlier. Is there any reason you need to have that constraint? I'll keep playing.

Sorry about the slow response time on this, holidays.

**Comment by JasonXtreme** [comment] 2019-01-03 09:40
Hi, no prob, my responses were slow even without the holidays ;) Happy new year!

Yes, as I've mentioned, I use several libraries, one of them is AutoBogus, which has a constructor such as:

`var object = new AutoFaker<T>();`

This creates a mocked representation of the class T, which is generally defined somewhere else and retrieved using generics and reflections. I'd be glad to share the code if you're interested, but I believe it has no effect on the issue at hand. Bottom line, AutoFaker has a constraint on the generic T that it needs to be a class.

**Comment by mattfrear** [comment] 2019-01-03 10:17
I am also still in my holidays, and it's late so I'm struggling too!

I kept playing with it before seeing your last reply, attempted to write a failed test again:

```csharp
        private class GenericExampleProvider<T> : IExamplesProvider<T> where T : class
        {
            public T GetExamples()
            {
                if (typeof(T) == typeof(PersonRequest))
                {
                    return (T)(object)new PersonRequest { FirstName = "Steve" };
                }

                return default(T);
            }
        }

        [Fact]
        public void Apply_WhenExampleProviderIsGenericAndRequestIsANullableGuid_ShouldNotThrowException()
        {
            // Arrange
            serviceProvider.GetService(typeof(IExamplesProvider<PersonRequest>)).Returns(new GenericExampleProvider<PersonRequest>());
            var personRequestParameter = new BodyParameter { In = "body", Schema = new Schema { Ref = "#/definitions/PersonRequest" } };
            var operation = new Operation { OperationId = "foobar", Parameters = new[] { personRequestParameter } };
            var parameterDescriptions = new List<ApiParameterDescription>() { new ApiParameterDescription { Type = typeof(PersonRequest) } };
            var filterContext = FilterContextFor(typeof(FakeActions), nameof(FakeActions.PersonRequestUnannotated), parameterDescriptions);

            // Act
            sut.Apply(operation, filterContext);

            // Assert
            var actualSchemaExample = (JObject)filterContext.SchemaRegistry.Definitions["PersonRequest"].Example;
            actualSchemaExample["firstName"].ShouldBe("Steve");
        }
```

I'm still not sure how to write this failing test. Maybe I need AutoBogus, which I haven't seen before.

**Comment by JasonXtreme** [comment] 2019-01-03 11:47
I'm pretty sure you don't need AutoBogus, having the constraint there is enough, you just need a way to pass a non-class parameter to the GenericExampleProvider<T>, which the compiler should stop your from doing unless you're using reflection, I'm guessing. It does somehow happen during runtime, causing the exception. I'll see if I can trace it down in the source code and give you a hint on how to reproduce it in tests. Hang tight.

**Comment by JasonXtreme** [comment] 2019-01-03 12:09
You could use a derivative from the source, like so (again, from heart, haven't tried compiling):

``` cs
        [Fact]
        public void Apply_WhenExampleProviderIsGenericAndRequestIsANullableGuid_ShouldNotThrowException()
        {
            // Arrange
            var type = typeof(Nullable<Guid>);
            var exampleProviderType = typeof(IExamplesProvider<>).MakeGenericType(type);
            var instanceProviderType = typeof(GenericExampleProvider<>).MakeGenericType(type); //Untested, might (should) throw, I'm guessing this is what serviceProvider.GetService does in the background
            serviceProvider.GetService(exampleProviderType ).Returns(Activator.CreateInstance(instanceProviderType )); //In case the previously commented line does not throw, this is what should throw immediately. I guess you don't need the rest.
            var personRequestParameter = new BodyParameter { In = "body", Schema = new Schema { Ref = "#/definitions/PersonRequest" } };
            var operation = new Operation { OperationId = "foobar", Parameters = new[] { personRequestParameter } };
            var parameterDescriptions = new List<ApiParameterDescription>() { new ApiParameterDescription { Type = typeof(Nullable<Guid>) } };
            var filterContext = FilterContextFor(typeof(FakeActions), nameof(FakeActions.PersonRequestUnannotated), parameterDescriptions);

            // Act
            sut.Apply(operation, filterContext);

            // Assert
            var actualSchemaExample = (JObject)filterContext.SchemaRegistry.Definitions["PersonRequest"].Example;
            actualSchemaExample["firstName"].ShouldBe("Steve");
        }
```

Let me know if you need anything else :)

**Comment by mattfrear** [comment] 2019-05-30 04:42
I'm going to close this issue as I couldn't reproduce it.

**Closed by mattfrear** 2019-05-30 04:42 UTC
