### ISSUE TITLE
AppendAuthorizeToSummaryOperationFilter appends found Roles instead of overriding

### ISSUE THREAD

**Issue by snebjorn** [mattfrear/Swashbuckle.AspNetCore.Filters#249] opened 2024-06-07 12:41 UTC
It appears that `options.OperationFilter<AppendAuthorizeToSummaryOperationFilter>();` is appending the found roles instead of overriding.

Given this controller
```cs
[Authorize(Roles = "Foo, Bar")]
[ApiController]
[Route("[controller]")]
public class HelloController : ControllerBase
{
    [HttpGet]
    public async Task<ActionResult> Get() {}

    [HttpDelete("{id}")]
    [Authorize(Roles = "Bar")]
    public async Task<ActionResult> Delete([FromRoute] int id) {}
}
```

The UI will look like this
```
GET /hello (Auth roles: Foo, Bar)
DELETE /hello/{id} (Auth roles: Bar, Foo, Bar)
```

I'm pretty sure `[Authorize(Roles = "Bar")]` on Delete overrides `[Authorize(Roles = "Foo, Bar")]` on the controller.

The expected output is
```
GET /hello (Auth roles: Foo, Bar)
DELETE /hello/{id} (Auth roles: Bar)
```

**Comment by mattfrear** [comment] 2024-06-09 21:00
I'm gonna close this issue because it's a duplicate of #144 which is still open.

You're welcome to fix it via a PR.

**Closed by mattfrear** 2024-06-09 21:00 UTC
