### ISSUE TITLE
Automatic examlpe annotation does not respect `System.Text.Json` options

### ISSUE THREAD

**Issue by lawrence-laz** [mattfrear/Swashbuckle.AspNetCore.Filters#157] opened 2020-07-29 11:37 UTC
Adding `JsonStringEnumConverter` to `System.Text.Json` options makes `Model` tab in Swagger UI display enums as strings, but automatically annotated examples through `IExamplesProvider<T>` don't convert enum values to strings in `Example Value` tab.

**Comment by mattfrear** [comment] 2020-07-30 03:52
Duplicate of #132 .

We use Newtonsoft to generate the JSON in examples. I might one day get System.Text.Json to work, I've tried in the past.

**Closed by mattfrear** 2020-07-30 03:52 UTC

**Comment by mattfrear** [comment] 2020-09-27 20:08
This should be fixed now https://www.nuget.org/packages/Swashbuckle.AspNetCore.Filters/6.0.0
