### ISSUE TITLE
Error in dotnetcore2.2: Method 'Apply' does not have an implementation

### ISSUE THREAD

**Issue by Sti2nd** [mattfrear/Swashbuckle.AspNetCore.Filters#113] opened 2019-09-26 13:36 UTC
Using dotnetcore2.2 and getting the following error:

Unhandled Exception: System.TypeLoadException: Method 'Apply' in type 'Swashbuckle.AspNetCore.Filters.ExamplesOperationFilter' from assembly 'Swashbuckle.AspNetCore.Filters, Version=4.5.5.0, Culture=neutral, PublicKeyToken=aa1e9c5053bfbe95' does not have an implementation.

In Startup.cs I have

```C#
services.AddSwaggerExamplesFromAssemblyOf<AnimalExample>();
```

and in the services.AddSwaggerGen method I call `c.ExampleFilters();`

My AnimalExample.cs:

```C#
using Swashbuckle.AspNetCore.Filters;

namespace webAPI.Models
{
    // Used by Swagger (Swashbuckle.AspNetCore.Filters extension) to generate examples
    public class AnimalExample : IExamplesProvider<Animal>
    {
        public Animal GetExamples()
        {
            return new Animal
            {
                Id = "1",
                Name = "Rex",
                TypeOfAnimal = 0
            };
        }
    }
}
```

**Comment by mattfrear** [comment] 2019-09-26 22:29
Sounds strange. I'm using it with .NET Core 2.2 without problems. Can you post the Swagger related stuff from your Startup.cs?

**Comment by Sti2nd** [comment] 2019-09-27 07:26
I just pasted the whole Startup.cs in case other libraries might clash:

```C#
using System;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using webAPI.Models;
using webAPI.Services;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.Filters;

namespace webAPI
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<FeedMeDatabaseSettings>(Configuration.GetSection(nameof(FeedMeDatabaseSettings)));
            services.AddSingleton<IFeedMeDatabaseSettings>(s => s.GetRequiredService<IOptions<FeedMeDatabaseSettings>>().Value);
            services.AddSingleton<DbService>();

            services.AddMvc()
                .AddJsonOptions(options => options.UseMemberCasing())
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

            services.AddSwaggerExamplesFromAssemblyOf<AnimalExample>();

            services.AddSwaggerGen(c =>
            {

                c.SwaggerDoc("v1", new OpenApiInfo 
                { 
                    Title = "webAPI", 
                    Version = "v1",
                    Description = "The API for FeedMe",
                    Contact = new OpenApiContact
                    {
                        Name = "",
                        Email = "",
                    },
                    License = new OpenApiLicense
                    {
                        Name = "Licence",
                        Url = new Uri("https://example.com/license"),
                    }
                });

                // [SwaggerRequestExample] & [SwaggerResponseExample]
                c.ExampleFilters();

                // Set the comments path for the Swagger JSON and UI.
                var xmlFile = $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = System.IO.Path.Combine(AppContext.BaseDirectory, xmlFile);
                c.IncludeXmlComments(xmlPath);

            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();

            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "webAPI v1");
            });

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "api/{controller}/{action}/{id?}");
            });

        }
    }
}

```

**Comment by mattfrear** [comment] 2019-10-11 08:13
I don't know, I can't reproduce this. I'm using .NET Core 2.2 and Swashbuckle.AspNetCore.Filters 4.5.5 at work without problems. It seems like something funky is going on in your solution.

A quick google and it sounds like a tricky issue: https://stackoverflow.com/questions/948785/typeloadexception-says-no-implementation-but-it-is-implemented

Sorry, but I'm going to close this as I can't reproduce.

**Closed by mattfrear** 2019-10-11 08:13 UTC

**Comment by elladan06** [comment] 2019-11-15 13:47
I had the same problem. It was due to Swashbuckle.AspNetCore and Swashbuckle.AspNetCore.Filters wasn't at the same version. In my case, Swashbuckle.AspNetCore was at 5.0.0-rc4 and Swashbuckle.AspNetCore.Filter was at 4.5.5. So I updated Swashbuckle.AspNetCore.Filter and the problem was fixed.
