### ISSUE TITLE
FormatterNotFoundException for text/csv upgrading to 7.0.6

### ISSUE THREAD

**Issue by ehavelaarsnz** [mattfrear/Swashbuckle.AspNetCore.Filters#224] opened 2023-04-21 01:07 UTC
We have an API using Swashbuckle.AspNetCore.Filters v7.0.3.  It has a POST method that can have responses formatted as JSON or CSV.

Works great, and in the example on the Swagger UI, I can select response media type `application/json` or `text/csv` and the example is formatted appropriately.

But if I upgrade the Nuget package to v7.0.6, the API startup fails with a complaint about `text/csv`:

```
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - MyCompany.MyProjecty.API.Controllers.MyController.PostData (MyCompany.MyProject.API). See inner exception
 ---> Swashbuckle.AspNetCore.Filters.MvcOutputFormatter+FormatterNotFoundException: OutputFormatter not found for 'text/csv'
   at Swashbuckle.AspNetCore.Filters.MvcOutputFormatter.Serialize[T](T value, MediaTypeHeaderValue contentType)
   at Swashbuckle.AspNetCore.Filters.ExamplesConverter.SerializeExampleCsv(Object value)
   at Swashbuckle.AspNetCore.Filters.ResponseExample.<>c__DisplayClass3_0.<SetSingleResponseExampleForStatusCode>b__2()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Swashbuckle.AspNetCore.Filters.ResponseExample.SetSingleResponseExampleForStatusCode(KeyValuePair`2 response, Object example, ExamplesConverter examplesConverter)
   at Swashbuckle.AspNetCore.Filters.ResponseExample.SetResponseExampleForStatusCode(OpenApiOperation operation, Int32 statusCode, Object example)
   at Swashbuckle.AspNetCore.Filters.ServiceProviderExamplesOperationFilter.SetResponseExamples(OpenApiOperation operation, OperationFilterContext context)
   at Swashbuckle.AspNetCore.Filters.ServiceProviderExamplesOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   --- End of inner exception stack trace ---
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

How do we unbreak this?

**Comment by ehavelaarsnz** [comment] 2023-04-25 23:56
@mattfrear It works in version 7.0.3 and fails in version 7.0.4.  If I roll back it works again.

The API is in .NET 7.0 and has been for some months.  It has been through several versions of .NET in the past, so there could be some vestigial stuff in there I suppose.  But not trying to upgrade right now, no.

The full list of other Nuget packages in the project is:

``` xml
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.21.0" />
<PackageReference Include="Microsoft.FeatureManagement.AspNetCore" Version="2.5.1" />
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="7.0.6" ExcludeAssets="All" />
<PackageReference Include="Serilog.AspNetCore" Version="6.1.0" />
<PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
<PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="4.0.0" />
<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.5.0" />
<PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
```

**Comment by mattfrear** [comment] 2023-05-01 01:58
Hmm. I've tried twice but I can't reproduce this. 

I've created a brand new .NET 7 Web API application, with the standard Program.cs, and installed `<PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="7.0.6" />`.

I then follow the installation instructions for this package and add a quick example and the response example renders.

Are you doing something custom with supported media types or something? (maybe in your Program.cs)

**Comment by ehavelaarsnz** [comment] 2023-05-05 00:17
Well, we are adding a filter to the `SwaggerGenOptions` like so
``` c#
        options.DocumentFilter<MyResponseExampleCsvFilter>();
```
and the filter's `Apply()` does this:

``` c#
            //Retrievs all POST endpoints with 200 return.
            var validEndpoints = swaggerDoc.Paths.Values.SelectMany(x => x.Operations).Where(y => y.Key == OperationType.Post && y.Value.Responses.ContainsKey("200")).ToList();

            foreach (var endpoint in validEndpoints)
            {
                //Retrieves adequate mediaTypeEntries
                foreach (var mediaTypeEntry in endpoint.Value.Responses.FirstOrDefault(x => x.Key == "200").Value.Content)
                {
                    if (mediaTypeEntry.Key == "text/csv")
                    {
                        var provider = new MyResponseExample();
                        StreamReader reader = new StreamReader(_csvFormatterService.FormatMyResponseToCsv(provider.GetExamples()));
                        mediaTypeEntry.Value.Example = new OpenApiString(reader.ReadToEnd());
                    }
                }
            }
```

**Comment by mattfrear** [comment] 2023-05-05 05:00
Thanks. I can reproduce by adding `[Produces(MediaTypeNames.Application.Json,  "text/csv")]` to my controller. To be continued...

**Comment by mattfrear** [comment] 2023-05-08 05:15
I've spent over an hour debugging, trying to understand what's going on here.
I'm wondering if it's crashing because your API isn't configured correctly.
Does your API support text/csv responses? i.e. if you send it an Accept header via Postman, do you get a CSV response, like this:
![image](https://user-images.githubusercontent.com/169179/236739580-5f9b9784-de88-46ba-a408-8cae64813429.png)


If it does support CSV, can you please explain how you're configuring CSV in your Program.cs?

**Comment by ehavelaarsnz** [comment] 2023-05-08 21:10
Yes, it does support CSV; we generate it ourselves, effectively in the controller; I don't think `Program.cs` comes into it.  Our API returns a `FileContentResult` for JSON or a `FileStreamResult` for CSV.

The code to generate the response looks a lot like this:

``` c#
private ActionResult ConvertToFileContentResult(MyResponse responseToFormat)
{
    
        // ... code to parse the Accept header omitted ...
        
        switch (acceptHeader)
        {
            case null:
            case "":
            case "*/*":
            case "application/json":
                var jsonResult = JsonSerializer.SerializeToUtf8Bytes(responseToFormat, _myOptions);
                return File(jsonResult, "application/json; charset=utf-8");

            case "text/csv":
                var csvResult = FormatMyResponseToCsv(responseToFormat);
                return File(csvResult, "text/csv;header=present");

            default:
                // ... throw an exception ...
        }
    }
}

private MemoryStream FormatConfidentialityResponseToCsv(MyResponse input)
{
    // ... code to write CSV to a MemoryStream goes here...
}
```

**Comment by mattfrear** [comment] 2023-06-02 04:19
Thanks for the extra detail. This seems like an edge case to me, because your API doesn't return CSV the standard way which is via an OutputFormatter.

My options are
1. Do nothing. This is an edge case. OR
1. Change my code so that I don't throw an exception if an OutputFormatter is not found. I don't like this option, because the exception is useful information. OR
1. Add config to not conditionally not throw the exception for this use case.

I'm leaning towards option 1 right now. If there are other users of this library that get this exception which proves that this is not a one-off edge case, then I would do option 3 in the future. I'll close this Issue for now.

**Closed by mattfrear** 2023-06-02 04:19 UTC

**Comment by ehavelaarsnz** [comment] 2023-06-05 21:21
Ok @mattfrear , so do you have any suggestions for a work-around for our edge case?

**Comment by mattfrear** [comment] 2023-06-05 22:49
Confession - I haven't played with CSV examples much myself.

When CSV support was added in #208 by @icnocop, he used an OutputFormatter from WebApiContrib.Core.Formatter.Csv.

You _could_ use that package and then register it with `.AddCsvSerializerFormatters()`.

I just found this, which shows how to create your own CSV Media Formatter if you don't want to use the above package: https://learn.microsoft.com/en-us/aspnet/web-api/overview/formats-and-model-binding/media-formatters

Now my `ExamplesOperationFilter` won't throw its exception. You could probably remove your `MyResponseExampleCsvFilter` as my ExamplesOperationFilter will now be writing CSV examples.

One you've added a CSV media formatter you might also be able to cleanup your controllers and remove the `switch (acceptHeader)` and let Web API's Media Formatters do all that work for you.

Or... stay using `7.0.3` of my package.
